app/user/models.py
from app.extensions import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.urls import url_encode
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(200), unique=True, nullable=False)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

app/user/forms.py
from app.user.models import User
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, EmailField, SubmitField
from werkzeug.urls import url_encode


from wtforms.validators import DataRequired, Email, ValidationError


class SignupForm(FlaskForm):
    name = StringField('name', validators=[DataRequired()])
    username = StringField('username', validators=[DataRequired()])
    email = EmailField('E-mail', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Sign Up')

    def validate_email(self, email):
        email = User.query.filter_by(email=email.data).first()
        if email:
            raise ValidationError('This Email Is Already Taken!')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('This Username Is Already Taken!')


class LoginForm(FlaskForm):
    email = EmailField('E-mail', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')
    def validate_email(self, email):
        email = User.query.filter_by(email=email.data).first()
        if not email:
            raise ValidationError('Account with This E-mail does not Exist!')

app/user/__init__.py
from flask import Blueprint
from werkzeug.urls import url_encode



user = Blueprint('user', __name__, template_folder='templates', static_folder='static')

from . import routes

app/user/routes.py
from app.extensions import db
from app.user import user
from app.user.models import User
from app.user.forms import SignupForm, LoginForm
from flask import render_template, redirect, url_for
from flask_login import login_user, logout_user

@user.route('/signup', methods=['get', 'post'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        user = User(name=form.name.data, username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        return "<h1>User Added</h1>"
    return render_template('signup.html', form=form)

@user.route('/login', methods=['get', 'post'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            return "User Loged In"
    return render_template('login.html', form=form)

@user.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('user.login'))

app/user/templates/login.html
{%from 'macros/form.html' import render_form%}
{%extends 'layout.html'%}

{%block body%}
<section class="hero is-fullheight is-justify-content-center">
    <div class="columns is-justify-content-center is-align-items-center">
        <div class="column is-one-quarter">
            <img src="https://source.unsplash.com/400x600/?mobile" alt=""
                 class="is-4by5">
        </div>

        <div class="column is-one-quarter">
            <div class="box p-6">
                <h1 class="title has-text-centered">Login</h1>
                <p class="subtitle has-text-centered">To InstaFlask!</p>
                <form action="" method="post">
                    {{form.hidden_tag()}}
                    <div class="field my-3">
                        <p class="control has-icons-left has-icons-right">
                            {{render_form(form.email, class='input', placeholder="Email")}}
                            <span class="icon is-small is-left">
                            <i class="fas fa-envelope"></i>
                        </span>
                            <span class="icon is-small is-right">
                            <i class="fas fa-check"></i>
                        </span>
                        </p>
                    </div>

                    <div class="field my-3">
                        <p class="control has-icons-left">
                            {{render_form(form.password, class='input', placeholder="Password")}}
                            <span class="icon is-small is-left">
                        <i class="fas fa-lock"></i>
                    </span>
                        </p>
                    </div>

                    <div class="control my-3">
                        {{render_form(form.submit, class='button is-link is-fullwidth is-medium')}}
                    </div>
                </form>
            </div>
            <div class="box my-2">
                <p class="is-size-6 has-text-centered">Don't have an account? <a href="{{url_for('user.signup')}}">Sign Up!</a></p>
            </div>
        </div>
    </div>
</section>
{%endblock body%}

app/user/templates/signup.html
{%from 'macros/form.html' import render_form%}
{%extends 'layout.html'%}

{%block body%}
<section class="hero is-fullheight is-justify-content-center">
    <div class="box column is-one-third is-offset-one-third">
        <h5 class="title has-text-centered">InstaFlask</h5>
        <p class="subtitle has-text-centered">Sing up to see photos and videos from your friends.</p>
        <form action="" method="post">
            {{form.hidden_tag()}}
            <div class="field my-2">
                <p class="control has-icons-left has-icons-right">
                    {{render_form(form.email, class='input', placeholder="Email")}}
                    <span class="icon is-small is-left">
                        <i class="fas fa-envelope"></i>
                    </span>
                    <span class="icon is-small is-right">
                        <i class="fas fa-check"></i>
                    </span>
                </p>
            </div>

            <div class="control my-2">
                {{render_form(form.name, class='input', placeholder="Full Name")}}
            </div>

            <div class="control my-2">
                {{render_form(form.username, class='input', placeholder="Username")}}
            </div>

            <div class="field my-2">
                <p class="control has-icons-left">
                    {{render_form(form.password, class='input', placeholder="Password")}}
                    <span class="icon is-small is-left">
                        <i class="fas fa-lock"></i>
                    </span>
                </p>
            </div>

            <div class="control my-2">
                {{render_form(form.submit, class='button is-link is-fullwidth is-medium')}}
            </div>
        </form>
    </div>
</section>
{%endblock body%}